name: MinyonPlugin
main: MinyonPlugin\Main
version: 1.0.0
api: 5.0.0
author: eeT
description: Minyon mining plugin

commands:
  minyon:
    description: Minyon oluşturur
    usage: "/minyon"
    permission: minyon.use

permissions:
  minyon.use:
    description: "Minyon oluşturma izni"
    default: true
