name: Minion
version: 1.0.0
main: CLADevs\Minion\Main
api: 5.0.0
load: POSTWORLD
commands:
  minion:
    description: Minion komutları
    usage: "/minion"
    permission: minion.command
permissions:
  minion.command:
    default: true
